### ISSUE TITLE
SkyUI Compatibility Patch

### ISSUE THREAD

**Issue by Elscrux** [schlangster/skyui#92]
Hi, I'd like to ask for permission to upload some modified SkyUI interface files as part of a compatibility patch for Beyond Skyrim https://www.nexusmods.com/skyrimspecialedition/mods/10917.
We have implemented new map markers and quest artwork, but this implementation isn't compatible with SkyUI which is disastrous, as SkyUI is such an essential mod. Because of this, we made a patch for SkyUI which includes modified versions of the files map.swf, mapMarkerArt.swf, quest_journal.swf, buttonart.swf, and configpanel.swf. However, according to the nexus page, we need your permission to modify and upload even some of the files of the mod and we couldn't reach anyone from the old team other anywhere else.
I already made an issue here on GitHub about this but after the first "No", I didn't get an answer https://github.com/schlangster/skyui/issues/88. I respect that of course, but as I felt like I failed to describe the situation accordingly which might have led to the initial rejection, this is now my second attempt to reach you and have a conversation :-)

**Comment by EdwardBlair** [comment]
I’m sure you’re aware; this code isn’t up to date, and latest (v5.x) isn’t publicly available

impressive you’ve got it working on Xbox. Wasn’t even aware that was a thing!

Main concern from me with came from ensuring modified distributions of skyui components were kept up to date, and what happens if they’re not! Easily mitigated by just blanket denying (or only allowing ancillary parts to be overridden, I.e. button art and map markers). That said, very unlikely skyui will have any more updates. Until Todd releases Skyrim Ultimate Edition. Ha. 

To better understand scope of this:

Have you added new quest markers - or are you overriding existing ones?

You are wanting to add new quest art - I never assumed anyone would want to replace this so did not separate quest art into a separate swf (similar to button art and quest markers) which is unfortunate as a replacement quest journal is a necessity in that instance.

**Comment by Mardoxx** [comment]
I’m sure you’re aware; this code isn’t up to date, and latest (v5.x) isn’t publicly available

impressive you’ve got it working on Xbox. Wasn’t even aware that was a thing!

Main concern from me with came from ensuring modified distributions of skyui components were kept up to date, and what happens if they’re not! Easily mitigated by just blanket denying (or only allowing ancillary parts to be overridden, I.e. button art and map markers). That said, very unlikely skyui will have any more updates. Until Todd releases Skyrim Ultimate Edition. Ha.

To better understand scope of this:

Have you added new quest markers - or are you overriding existing ones?

You are wanting to add new quest art - I never assumed anyone would want to replace this so did not separate quest art into a separate swf (similar to button art and quest markers) which is unfortunate as a replacement quest journal is a necessity in that instance.

(Replied with the right account this time lol)

**Comment by Elscrux** [comment]
The first thing to note is that I didn't actually use the code presented here in this GitHub repo. I only wrote here, in an attempt to reach someone. I used https://github.com/jindrapetrik/jpexs-decompiler to edit the most up-to-date version of SkyUI from nexus - and I'd do that again for any updates of course.

I added new map markers, I didn't replace them. I had to modify map.swf to add more entries to the ICON_MAP array and to add additional map markers to list the list of markers that are displayed slightly larger (for city markers). So for this use case, sadly edits to map.swf are necessary. The new map marker art was added to mapMarkerArt.swf.
The quest artwork expansion worked similarly, but as you said, that is part of quest_journal.swf only.
I don't remember why I also included buttonart.swf and configpanel.swf. I didn't actually change anything about them. I think they were linked to by the other SWF files, so I had to include them. I'll check again.

We can run the updated interface files without installing anything else SkyUI or SKSE. We didn't test it on Xbox yet, but as long as Xbox doesn't have very different interface files, the additional map markers will most likely work too.
When you'd install SkyUI next to Beyond Skyrim, everything would work out of the box, without the need to install any additional patch or anything like that. We tested this extensively in the last 6 months and didn't find any issues. I felt like this patchless approach is the best-case scenario for end users. The only thing that can happen is that SkyUI files would overwrite Beyond Skyrim files. In this case, the new map markers would vanish, but the core of SkyUI would work.

I fully understand that you want to ensure everybody has up-to-date files. The only thing I can do about this is to give you my word that I will make sure to always keep our versions up-to-date with the nexus release. As we're a big modding project, there will always be someone to handle a SkyUI update, if that ever happens.
So if you could permit us to do this, that'd be very helpful. Otherwise, we're not going to investigate this any further as releasing a version that isn't compatible with SkyUI doesn't make any sense as nobody would use it, which would be a shame.

**Comment by Elscrux** [comment]
@Mardoxx Sorry for the ping. I just want to make sure you didn't forget about this.

**Comment by EdwardBlair** [comment]
Yeah, go for it!

**Comment by Mardoxx** [comment]
Yeah go for it. I was trying to think of the least intrusive way to do it but I think the way you described is easiest.

**Comment by Elscrux** [comment]
Thanks a lot! We'll make sure to always keep the files up to date and credit the SkyUI team of course.
